# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangoql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=djangoql.models.get_favorite_query_name, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Query text')),
                ('scope', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10, verbose_name='Scope')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_query_list', to='contenttypes.ContentType', verbose_name='Content Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_query_list', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite query',
                'verbose_name_plural': 'Favorite queries',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritequery',
            unique_together=set([('text', 'content_type', 'user')]),
        ),
    ]
